### ISSUE TITLE
Suche Aufgaben zum Thema: Summenzeichen

### ISSUE THREAD

**Issue by TatjanaMerkel** [TatjanaMerkel/complete-induction#7]
Beispiel: Buch
https://www.amazon.de/Vollständige-Induktion-Beispiele-Aufgaben-Umfallen/dp/3662586320

Hinweis: Online im HSRM Bibliothek erhältlich
- digital aufschreiben
-Json

**Comment by TatjanaMerkel** [comment]
5 Beispiele

**Comment by yendeus** [comment]
Kleine Vorschau: :)

`{
    "Aufgaben": [
        {
            "Aufgabenname": "Aufgabe 1",
            "Kategorien": [
                "Summenzeichen"
            ],
            "Schwierigkeit": "leicht",
            "Beschränkung": 1,
            "Zahlenraum": "natürliche Zahlen",
            "Aufgabenstellung": "SUM(n, 1,(2*i-1)) = Math.pow(n,2)",
            "Rechenschritte_links": [
                "SUM(n+1, 1,(2*i-1))",
                "SUM(n, 1,(2*i-1)) + (2*(n+1)-1)",
                "Math.pow(n,2) + (2*(n+1)-1)",
                "Math.pow(n,2) + 2*n + 2-1",
                "Math.pow(n,2) + 2*n + 1",
                "Math.pow(n+1,2)"
            ],
            "Rechenschritte_rechts": [
                "Math.pow(n+1,2)",
                "Math.pow(n,2) + 2*n + 1"
            ]
        },
        {
            "Aufgabenname": "Aufgabe 2",
            "Kategorien": [
                "Summenzeichen"
            ],
            "Schwierigkeit": "mittel",
            "Beschränkung": 1,
            "Zahlenraum": "natürliche Zahlen",
            "Aufgabenstellung": "SUM(n, 1,(1/((3*i-1)*(3*i+1))) = (n/(3*n+1))",
            "Rechenschritte_links": [
                "SUM(n+1, 1,(1/((3*i-1)*(3*i+1)))]",
                "SUM(n, 1,(1/((3*i-1)*(3*i+1))) + 1/((3*(n+1)-2)*(3*(n+1)+1)",
                "n/(3*n+1) + 1/((3*(n+1)-2)*(3*(n+1)+1)1",
                "n/(3*n+1) + 1/((3*n+1)*(3*n+4))",
                "(n*(3*n+4))/((3*n+1)*(3*n+4)) + 1/((3*n+1)*(3*n+4))",
                "(n*(3*n+4)+1)/((3*n+1)*(3*n+4))",
                "(3*Math.pow(n,2)+4*n+1)/((3*n+1)*(3*n+4))",
                "(3*n+1)*(n+1)/((3*n+1)*(3*n+4))"
            ],
            "Rechenschritte_rechts": [
                "(n+1)/(3*(n+1)+1)",
                "(n+1)/(3*n+3+1)",
                "(n+1)/(3*n+4)",
                "(n+1)/(3*n+4)",
                "(3*n+1)*(n+1)/((3*n+1)*(3*n+4))"
            ]
        },
        {
            "Aufgabenname": "Aufgabe 3",
            "Kategorien": [
                "Summenzeichen"
            ],
            "Schwierigkeit": "mittel",
            "Beschränkung": 1,
            "Zahlenraum": "natürliche Zahlen",
            "Aufgabenstellung": "SUM(n, 1,Math.pow(i,3) = Math.pow((n*(n+1))/2),2)",
            "Rechenschritte_links": [
                "SUM(n+1, 1,Math.pow(i,3)",
                "SUM(n, 1,Math.pow(i,3) + Math.pow(n+1,3)",
                "Math.pow((n*(n+1))/2),2) + Math.pow(n+1,3)",
                "(Math.pow(n,2)*Math.pow(n+1,2))/4 + Math.pow(n+1,3)",
                "(Math.pow(n,2)*Math.pow(n+1,2))/4 + 4*Math.pow(n+1,3)/4",
                "(Math.pow(n,2)*Math.pow(n+1,2)+ 4*Math.pow(n+1,3))/4",
                "(Math.pow(n,2)*Math.pow(n+1,2)+ 4*Math.pow(n+1,2)*(n+1)/4",
                "(Math.pow(n+1,2)*(Math.pow(n,2)+ 4*n +4))/4",
                "(Math.pow(n+1,2)*Math.pow(n+2,2))/4",
                "Math.pow(((n+1)*(n+2))/2),2"
            ],
            "Rechenschritte_rechts": [
                "Math.pow(((n+1)*((n+1)+1))/2),2",
                "Math.pow(((n+1)*(n+2))/2),2"
            ]
        },
        {
            "Aufgabenname": "Aufgabe 4",
            "Kategorien": [
                "Summenzeichen"
            ],
            "Schwierigkeit": "leicht",
            "Beschränkung": 0,
            "Zahlenraum": "natürliche Zahlen",
            "Aufgabenstellung": "SUM(n,0, 2*i = n*(n+1)",
            "Rechenschritte_links": [
                "SUM(n+1, 1,2*i",
                "SUM(n, 1,2*i + 2*(n+1)",
                "n*(n+1) + 2*(n+1)",
                "Math.pow(n,2) + n + 2*n+2",
                "Math.pow(n,2) + 3*n + 2"
            ],
            "Rechenschritte_rechts": [
                "(n+1)*((n+1)+1)",
                "(n+1)*(n+2)",
                "Math.pow(n,2) + n + 2*n + 2",
                "Math.pow(n,2) + 3*n + 2"
            ]
        },
        {
            "Aufgabenname": "Aufgabe 5",
            "Kategorien": [
                "Summenzeichen"
            ],
            "Schwierigkeit": "schwer",
            "Beschränkung": 1,
            "Zahlenraum": "natürliche Zahlen",
            "Aufgabenstellung": "SUM(n,1, m/Math.fac(m+1)) = 1-1/Math.fac(n+1)",
            "Rechenschritte_links": [
                "SUM(n+1,1, i/Math.fac(i+1))",
                "SUM(n,1, i/Math.fac(i+1)) + (n+1)/Math.fac((n+1)+1)",
                "SUM(n,1, i/Math.fac(i+1)) + (n+1)/Math.fac(n+2)",
                "1-1/Math.fac(n+1) + (n+1)/Math.fac(n+2)",
                "1-(n+2)/(Math.fac(n+1)*(n+2)) + (n+1)/(Math.fac(n+1)*(n+2))",
                "1+(-(n+2)+(n+1))/(Math.fac(n+1)*(n+2))",
                "1+(-(1)/(Math.fac(n+1)*(n+2))",
                "1-((1)/(Math.fac(n+2)"
            ],
            "Rechenschritte_rechts": [
                "1-((1)/(Math.fac((n+1)+1)",
                "1-((1)/(Math.fac(n+2)"
            ]
        }
    ]
}`
